exports.VOTE_PUBLIC_FIELDS = {
  quorumId: 1,
  type: 1,
  title: 1,
  shortDesc: 1,
  longDesc: 1,
  description: 1,
  result: 1,
  date: 1,
  congress: 1,
  termId: 1,
  rollCall: 1,
  readMore: 1,
  sbaPosition: 1,
  status: 1,
  createdAt: 1,
  updatedAt: 1,
  modifiedBy: 1,
  modifiedAt: 1,
};

exports.ACTIVITY_PUBLIC_FIELDS = {
  type: 1,
  title: 1,
  activityquorumId: 1,
  shortDesc: 1,
  longDesc: 1,
  rollCall: 1,
  readMore: 1,
  date: 1,
  congress: 1,
  termId: 1,
  trackActivities: 1,
  status: 1,
  modifiedBy: 1,
  modifiedAt: 1,
  createdAt: 1,
  updatedAt: 1,
};
